# Generated by Django 5.1.3 on 2024-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letadla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.TextField(default=4)),
                ('cena', models.IntegerField()),
                ('popis', models.TextField(blank=True)),
            ],
        ),
    ]
