# Generated by Django 5.1.3 on 2024-11-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Letadla',
            new_name='Letadlo',
        ),
    ]
